### ISSUE TITLE
problem with search in selections

### ISSUE THREAD

**Issue by arashackdev** [manishen/selection#1]
Hello there,

I spent some time debugging this, in this project you are using bootstrap 3 and this caused a problem. 
Since I am using bootstrap 4 I don't have .hide and .show; these syntaxes has changed to .d-none according to the link below.

[Bootstrap 4 Displays](https://getbootstrap.com/docs/4.1/utilities/display/)

Just for making this awesome repo more usable please either define the styles needed in the css file or make a note for others who intend to use it. If needed I'll be more than happy to help out too.

thanks a lot
jimist

**Comment by ataiemajid63** [comment]
> Hello there,
> 
> I spent some time debugging this, in this project you are using bootstrap 3 and this caused a problem.
> Since I am using bootstrap 4 I don't have .hide and .show; these syntaxes has changed to .d-none according to the link below.
> 
> [Bootstrap 4 Displays](https://getbootstrap.com/docs/4.1/utilities/display/)
> 
> Just for making this awesome repo more usable please either define the styles needed in the css file or make a note for others who intend to use it. If needed I'll be more than happy to help out too.
> 
> thanks a lot
> jimist

The hide and show classes are built in Selection component and not related to bootstrap 4.
